env: "testing"
application_name: upassed-submission-service
grpc_server:
    port: "44044"
    timeout: 10m
storage:
    host: localhost
    port: 5432
    database_name: upassed-submission-service-db
    user: user
    password: password
migrations:
    migrations_path: "../../../migration/scripts"
    migrations_table_name: migrations
services:
    authentication_service:
        host: localhost
        port: 44045
timeouts:
    endpoint_execution_timeout_ms: 60000
tracing:
    host: localhost
    port: 14268
    submission_tracer_name: submission-tracer
rabbit:
    user: upassed-rabbit-user
    password: upassed-rabbit-password
    host: localhost
    port: 5672
    exchange:
        name: upassed-submission-service
        type: direct
    queues:
        submission_create:
            name: submission-create-queue
            routing_key: submission.create
